/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryDescRecommend: typeof import('./src/components/Modules/ImageGeneration/CategoryDescRecommend.vue')['default']
    DrawList: typeof import('./src/components/Modules/ImageGeneration/DrawList.vue')['default']
    Headline: typeof import('./src/components/Modules/ImageGeneration/Headline.vue')['default']
    ImageList: typeof import('./src/components/Modules/ImageCommunity/ImageList.vue')['default']
    MessageModule: typeof import('./src/components/TabBar/AIChat/MessageModule.vue')['default']
    ParameterAdjustment: typeof import('./src/components/Modules/ImageGeneration/ParameterAdjustment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarDialog: typeof import('./src/components/TabBar/AIChat/SidebarDialog.vue')['default']
    SidebarItem: typeof import('./src/components/TabBar/AIChat/SidebarItem.vue')['default']
    WXTipsMask: typeof import('./src/components/Common/WXTipsMask.vue')['default']
  }
}
