/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  chat_assistant_category: () => import("@/views/chat/assistant/category/index.vue"),
  chat_assistant_view: () => import("@/views/chat/assistant/view/index.vue"),
  "chat_hot-issues": () => import("@/views/chat/hot-issues/index.vue"),
  chat_model: () => import("@/views/chat/model/index.vue"),
  home: () => import("@/views/home/index.vue"),
  recharge_goods: () => import("@/views/recharge/goods/index.vue"),
  recharge_order: () => import("@/views/recharge/order/index.vue"),
  usage: () => import("@/views/usage/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  "user-service_activation-code": () => import("@/views/user-service/activation-code/index.vue"),
  "user-service_dialog_all-dialog": () => import("@/views/user-service/dialog/all-dialog/index.vue"),
  "user-service_dialog_dialog-detail": () => import("@/views/user-service/dialog/dialog-detail/index.vue"),
  "user-service_dialog_star-dialog-detail": () => import("@/views/user-service/dialog/star-dialog-detail/index.vue"),
  "user-service_feedback": () => import("@/views/user-service/feedback/index.vue"),
  "user-service_promotion": () => import("@/views/user-service/promotion/index.vue"),
  "user-service_punch-in-daily": () => import("@/views/user-service/punch-in-daily/index.vue"),
  "user-service_task-reward": () => import("@/views/user-service/task-reward/index.vue"),
  "user-service_user": () => import("@/views/user-service/user/index.vue"),
};
