/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      hideInMenu: true,
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      hideInMenu: true,
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      hideInMenu: true,
      constant: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      order: 4,
      icon: 'carbon:chat'
    },
    children: [
      {
        name: 'chat_assistant',
        path: '/chat/assistant',
        meta: {
          title: 'chat_assistant',
          i18nKey: 'route.chat_assistant',
          icon: 'carbon:theater'
        },
        children: [
          {
            name: 'chat_assistant_category',
            path: '/chat/assistant/category',
            component: 'view.chat_assistant_category',
            meta: {
              title: 'chat_assistant_category',
              i18nKey: 'route.chat_assistant_category',
              icon: 'carbon:search-locate'
            }
          },
          {
            name: 'chat_assistant_view',
            path: '/chat/assistant/view',
            component: 'view.chat_assistant_view',
            meta: {
              title: 'chat_assistant_view',
              i18nKey: 'route.chat_assistant_view',
              icon: 'carbon:data-view-alt'
            }
          }
        ]
      },
      {
        name: 'chat_hot-issues',
        path: '/chat/hot-issues',
        component: 'view.chat_hot-issues',
        meta: {
          title: 'chat_hot-issues',
          i18nKey: 'route.chat_hot-issues',
          icon: 'carbon:chat-launch'
        }
      },
      {
        name: 'chat_model',
        path: '/chat/model',
        component: 'view.chat_model',
        meta: {
          title: 'chat_model',
          i18nKey: 'route.chat_model',
          icon: 'carbon:chat-operational'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'carbon:cloud-satellite-config',
      alertBanner: {
        message: '请谨慎修改配置信息，修改后需要重启 API 服务程序才可生效，若有疑问请联系开发者。',
        type: 'warning'
      }
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'recharge',
    path: '/recharge',
    component: 'layout.base',
    meta: {
      title: 'recharge',
      i18nKey: 'route.recharge',
      order: 3,
      icon: 'carbon:ibm-bluepay'
    },
    children: [
      {
        name: 'recharge_goods',
        path: '/recharge/goods',
        component: 'view.recharge_goods',
        meta: {
          title: 'recharge_goods',
          i18nKey: 'route.recharge_goods',
          icon: 'carbon:shopping-cart'
        }
      },
      {
        name: 'recharge_order',
        path: '/recharge/order',
        component: 'view.recharge_order',
        meta: {
          title: 'recharge_order',
          i18nKey: 'route.recharge_order',
          icon: 'carbon:border-left'
        }
      }
    ]
  },
  {
    name: 'usage',
    path: '/usage',
    component: 'layout.base$view.usage',
    meta: {
      title: 'usage',
      i18nKey: 'route.usage',
      icon: 'carbon:chart-line-data',
      order: 5
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true,
      icon: 'carbon:user-avatar'
    }
  },
  {
    name: 'user-service',
    path: '/user-service',
    component: 'layout.base',
    meta: {
      title: 'user-service',
      icon: 'carbon:user-avatar',
      i18nKey: 'route.user-service',
      order: 2
    },
    children: [
      {
        name: 'user-service_activation-code',
        path: '/user-service/activation-code',
        component: 'view.user-service_activation-code',
        meta: {
          title: 'user-service_activation-code',
          icon: 'carbon:sim-card',
          i18nKey: 'route.user-service_activation-code',
          alertBanner: {
            message:
              '输入正确的密码、对话和绘画次数，点击"生成"即可生成特有代码，可在客户端"我的服务 — 卡密兑换"中使用。'
          }
        }
      },
      {
        name: 'user-service_dialog',
        path: '/user-service/dialog',
        meta: {
          title: 'user-service_dialog',
          i18nKey: 'route.user-service_dialog',
          icon: 'carbon:chat-bot'
        },
        children: [
          {
            name: 'user-service_dialog_all-dialog',
            path: '/user-service/dialog/all-dialog',
            component: 'view.user-service_dialog_all-dialog',
            meta: {
              title: 'user-service_dialog_all-dialog',
              i18nKey: 'route.user-service_dialog_all-dialog',
              icon: 'carbon:list-boxes',
              alertBanner: {
                message: '用户新建的所有对话框在这里都可以看到。点击 ID 可跳转至对话详情。'
              }
            }
          },
          {
            name: 'user-service_dialog_dialog-detail',
            path: '/user-service/dialog/dialog-detail',
            component: 'view.user-service_dialog_dialog-detail',
            meta: {
              title: 'user-service_dialog_dialog-detail',
              i18nKey: 'route.user-service_dialog_dialog-detail',
              icon: 'carbon:text-indent'
            }
          },
          {
            name: 'user-service_dialog_star-dialog-detail',
            path: '/user-service/dialog/star-dialog-detail',
            component: 'view.user-service_dialog_star-dialog-detail',
            meta: {
              title: 'user-service_dialog_star-dialog-detail',
              i18nKey: 'route.user-service_dialog_star-dialog-detail',
              icon: 'carbon:star'
            }
          }
        ]
      },
      {
        name: 'user-service_feedback',
        path: '/user-service/feedback',
        component: 'view.user-service_feedback',
        meta: {
          title: 'user-service_feedback',
          i18nKey: 'route.user-service_feedback',
          icon: 'carbon:face-satisfied'
        }
      },
      {
        name: 'user-service_promotion',
        path: '/user-service/promotion',
        component: 'view.user-service_promotion',
        meta: {
          title: 'user-service_promotion',
          i18nKey: 'route.user-service_promotion',
          icon: 'carbon:airline-manage-gates',
          alertBanner: {
            message: '可点击复制"邀请人ID"和"被邀请人ID"到其他地方快捷查询。',
            type: 'success'
          }
        }
      },
      {
        name: 'user-service_punch-in-daily',
        path: '/user-service/punch-in-daily',
        component: 'view.user-service_punch-in-daily',
        meta: {
          title: 'user-service_punch-in-daily',
          i18nKey: 'route.user-service_punch-in-daily',
          icon: 'carbon:building'
        }
      },
      {
        name: 'user-service_task-reward',
        path: '/user-service/task-reward',
        component: 'view.user-service_task-reward',
        meta: {
          title: 'user-service_task-reward',
          i18nKey: 'route.user-service_task-reward',
          icon: 'carbon:task-approved',
          alertBanner: {
            message: '完成状态列的值对应：0=进行中，1=已完成，-1=已领取。',
            type: 'info'
          }
        }
      },
      {
        name: 'user-service_user',
        path: '/user-service/user',
        component: 'view.user-service_user',
        meta: {
          title: 'user-service_user',
          i18nKey: 'route.user-service_user',
          icon: 'carbon:user-profile',
          alertBanner: {
            message: '在行数据中右键可以自定义修改账户余额。'
          }
        }
      }
    ]
  }
];
