FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@10 --activate
RUN apk add --no-cache openssl libcrypto3

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 9091

CMD ["pnpm", "prod"]
